name: Subir pagina php a nginx

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Crear archivo private key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Con Rsync subir los archivos a el servidor remoto
        run: |
          rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./index.php ec2-user@${{ secrets.PUBLIC_IP_NGINX }}:/home/ec2-user/
          rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./MiProyecto ec2-user@${{ secrets.PUBLIC_IP_NGINX }}:/home/ec2-user/

      - name: Mover archivos a /var/www/html en la instancia
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.PUBLIC_IP_NGINX }} << 'EOF'
            sudo mv /home/ec2-user/index.php /usr/share/nginx/html/index.php
            sudo chown www-data:www-data /usr/share/nginx/html/index.php
            sudo chmod 644 /usr/share/nginx/html/index.php

            sudo mv /home/ec2-user/MiProyecto /usr/share/nginx/html/MiProyecto
            sudo chown -R www-data:www-data /usr/share/nginx/html/MiProyecto
            sudo chmod -R 755 /usr/share/nginx/html/MiProyecto

            sudo rm -f /usr/share/nginx/html/index.html
          EOF

      - name: Borrar archivo private key
        run: |
          rm -f deploy_key.pem
