name: RSYNC Files Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Crear un archivo temporal para la clave privada
      - name: Create private key file
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      # Subir el archivo index.html y la carpeta Pagina
      - name: Rsync files to remote server
        run: |
          rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./index.html ./Pagina/ ubuntu@44.223.71.116:/home/ubuntu/

      # Mover los archivos a /var/www/html en la instancia remota
      - name: Move files to /var/www/html on remote server
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ubuntu@44.223.71.116 << 'EOF'
            sudo mv /home/ubuntu/index.html /var/www/html/index.html
            sudo chown www-data:www-data /var/www/html/index.html
            sudo chmod 644 /var/www/html/index.html

            sudo mv /home/ubuntu/Pagina /var/www/html/Pagina
            sudo chown -R www-data:www-data /var/www/html/Pagina
            sudo chmod -R 755 /var/www/html/Pagina
          EOF

      # Limpiar el archivo de la clave privada temporal
      - name: Clean up private key file
        run: |
          rm -f deploy_key.pem
         
         
        
      
