name: RSYNC Files Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Subir el archivo index.html a la instancia remota y subir la carpeta Pagina y su contenido
      - name: Rsync index.html to remote server
        run: |
          
          rsync -avz -e "ssh -i ${{ secrets.DEPLOY_KEY }} -o StrictHostKeyChecking=no" ./index.html ubuntu@54.227.195.57:/home/ubuntu/

      - name: Rsync Pagina directory to remote server
        run: |
          rsync -avz -e "ssh -i ${{ secrets.DEPLOY_KEY }} -o StrictHostKeyChecking=no" ./Pagina/ ubuntu@54.227.195.57:/home/ubuntu/

      # Conectamos a la instancia remota y movemos los archivos y la carpeta a /var/www/html/
      - name: Move files to /var/www/html on remote server
        run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} -o StrictHostKeyChecking=no ubuntu@54.227.195.57 << 'EOF'
            sudo mv /home/ubuntu/index.html /var/www/html/index.html
            sudo chown www-data:www-data /var/www/html/index.html
            sudo chmod 644 /var/www/html/index.html

            sudo mv /home/ubuntu/Pagina /var/www/html/Pagina
            sudo chown -R www-data:www-data /var/www/html/Pagina
            sudo chmod -R 755 /var/www/html/Pagina
          EOF
         
         
        
      
