name: Subir pagina php

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Crear archivo private key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Con Rsync subir los archivos a el servidor remoto
        run: |
          rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./index.php ubuntu@${{ secrets.PUBLIC_IP }}:/home/ubuntu/
          rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./usuarios_blockDeNotas-mvc2 ubuntu@${{ secrets.PUBLIC_IP }}:/home/ubuntu/

      - name: Mover archivos a /var/www/html en la instancia
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.PUBLIC_IP }} << 'EOF'
            sudo mv /home/ubuntu/index.php /var/www/html/index.php
            sudo chown www-data:www-data /var/www/html/index.php
            sudo chmod 644 /var/www/html/index.php

            sudo mv /home/ubuntu/usuarios_blockDeNotas-mvc2 /var/www/html/usuarios_blockDeNotas-mvc2
            sudo chown -R www-data:www-data /var/www/html/usuarios_blockDeNotas-mvc2
            sudo chmod -R 755 /var/www/html/usuarios_blockDeNotas-mvc2

            sudo rm -f /var/www/html/index.html
          EOF

      - name: Borrar archivo private key
        run: |
          rm -f deploy_key.pem
