name: Subir pagina php

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Crear un archivo temporal para la clave privada
      - name: Create private key file
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      # Subir el archivo index.html y la carpeta Pagina
      - name: Rsync files to remote server
        run: |
          rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./index.php ubuntu@${{ secrets.PUBLIC_IP }}:/home/ubuntu/
          rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./usuarios_blockDeNotas-mvc2 ubuntu@${{ secrets.PUBLIC_IP }}:/home/ubuntu/

      # Mover los archivos a /var/www/html en la instancia remota
      - name: Move files to /var/www/html on remote server
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.PUBLIC_IP }} << 'EOF'
            sudo mv /home/ubuntu/index.html /var/www/html/index.php
            sudo chown www-data:www-data /var/www/html/index.php
            sudo chmod 644 /var/www/html/index.php

            sudo mv /home/ubuntu/Pagina /var/www/html/usuarios_blockDeNotas-mvc2
            sudo chown -R www-data:www-data /var/www/html/usuarios_blockDeNotas-mvc2
            sudo chmod -R 755 /var/www/html/usuarios_blockDeNotas-mvc2
          EOF

      # Limpiar el archivo de la clave privada temporal
      - name: Clean up private key file
        run: |
          rm -f deploy_key.pem
