name: SCP Files Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: rsync deployments
        uses: contention/rsync-deployments@v2.0.0
        with:
         flags: -avz --delete
         #excludes: |
         #  Archivos-tf
         #  *.tf
         #  *.tfstate
         #  *.tfvars
         #  README.md
         #  .github
         user: root
         host: 54.152.5.248
         localpath: ./Pagina
         remotepath: /var/www/html/
         deploy_key: ${{ secrets.DEPLOY_KEY }}

      - name: Upload index.html
        run: rsync -avz --delete ./index.html root@54.152.5.248:/var/www/html/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
         
         
        
      
