name: Destroy

on:
  workflow_dispatch:

jobs:
  destroy:  
    runs-on: ubuntu-latest
    steps:
    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch'
      run: terraform -chdir="Archivos tf" destroy -auto-approve
