name: Destroy Terraform

on:
  workflow_dispatch:   

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: 'us-east-1'

    - name: Terraform Init
      run: terraform init  

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
