name: Instalar y Generar JSDoc en S3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Configurar credenciales aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt install -y nodejs npm

      - name: Install jsdoc and generate documentation
        run: |
          sudo npm install -g jsdoc
          sudo jsdoc ./Pagina/funcion.js -d ./docs

      - name: Upload documentation to S3
        run: |
          aws s3 cp ./docs s3://${{ secrets.S3_BUCKET_NAME }}/Pagina --recursive

      - name: Eliminar carpeta docs
        run: |
          rm -rf ./docs
