name: Install and Generate JSDoc on EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Create private key file
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Run commands on EC2
        run: |
         ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@${{ secrets.PUBLIC_IP }} 'sudo apt-get update'

      - name: Install nodejs and npm on EC2
        run: |
         ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@${{ secrets.PUBLIC_IP }} '
         sudo apt-get install -y nodejs &&
         sudo apt install -y npm
         '

      - name: Install jsdoc and generate documentation
        run: |
         ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@${{ secrets.PUBLIC_IP }} '
         sudo npm install -g jsdoc &&
         jsdoc /var/www/html/Pagina/funcion.js -d /var/www/html/Pagina/docs
         '
