name: Install and Generate JSDoc on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Create private key file
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Run commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@${{ secrets.PUBLIC_IP }} "
          sudo apt-get update &&
          sudo apt-get install -y nodejs &&
          sudo apt install -y npm &&
          npm install -g jsdoc &&
          jsdoc ./path/to/archivo.js
          "
