name: phpUnit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      #He de deshabilitar el bloqueo de acceso publico sino no puedo habilitar el hosting
      - name: instalar composer
        run: composer require --dev phpunit/phpunit ^11
        
      - name: Remplazar composer.json en MiProyecto
        run: |
          cp ./composer.json ./MiProyecto/composer.json  

      - name: ejecutar el test
        run: php ./vendor/bin/phpunit
