name: phpUnit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      #He de deshabilitar el bloqueo de acceso publico sino no puedo habilitar el hosting
      - name: instalar composer
        working-directory: ./MiProyecto
        run: composer require --dev phpunit/phpunit ^10
        
      - name: Remplazar composer.json en MiProyecto
        run: cp ./composer.json ./MiProyecto/composer.json  

      - name: ejecutar el test
        working-directory: ./MiProyecto
        run: ./vendor/bin/phpunit
        continue-on-error: false  # Para que no detenga la ejecución del flujo si falla

      # Saber si ha pasado las pruebas o no
      - name: Verificar resultados de PHPUnit
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Todas las pruebas pasaron correctamente.";
          else
            echo "❌ Algunas pruebas fallaron.";
          fi
