name: Deploy s3 como servidor

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
        
      #- name: Installing Node.js
      #  uses: actions/setup-node@v4.1.0
      #  with:
      #    node-version: '16'
          
      #- name: Installing dependencies
      #  run: npm install
        
      #- name: Building project
      #  run: npm run build
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      #He de deshabilitar el bloqueo de acceso publico sino no puedo habilitar el hosting
      - name: Deshabilitar bloqueo de acceso público temporalmente
        run: |
         aws s3api put-public-access-block \
         --bucket ${{ secrets.AWS_S3_BUCKET }} \
         --public-access-block-configuration '{
          "BlockPublicAcls": false,
          "IgnorePublicAcls": false,
          "BlockPublicPolicy": false,
          "RestrictPublicBuckets": false
         }'

      - name: Habilitar el hosting de página web estática
        run: |
          aws s3 website s3://${{ secrets.AWS_S3_BUCKET }} --index-document index.html --error-document 404.html

      - name: Configurar la política de acceso público
        run: |
          aws s3api put-bucket-policy --bucket ${{ secrets.AWS_S3_BUCKET }} --policy '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::${{ secrets.AWS_S3_BUCKET }}/*"
              }
            ]
          }'

      - name: Subir a S3 bucket el index
        run: aws s3 cp ./index.html s3://${{ secrets.AWS_S3_BUCKET }}/index.html    

      - name: Subir a S3 bucket la carpeta Pagina  
        run: aws s3 sync ./Pagina s3://${{ secrets.AWS_S3_BUCKET }}/Pagina

      - name: Volver a habilitar el bloqueo de acceso público
        run: |
          aws s3api put-public-access-block \
          --bucket ${{ secrets.AWS_S3_BUCKET }} \
          --public-access-block-configuration '{
          "BlockPublicAcls": true,
          "IgnorePublicAcls": true,
          "BlockPublicPolicy": true,
          "RestrictPublicBuckets": true
          }' 
