name: Terraform AWS Deployment

#evento para que se deployee cuando se hace el push
#on:
#  push:   #evento a hacer en este caso cuando hagamos un push
#    branches:   #en la rama main
#      - main

#Este evento es para que solo se deployee si se lo digo manualmente
on:
 workflow_dispatch:

jobs:
  despliegue:   #nombre del job
    runs-on: ubuntu-latest   #maquina virtual en la que lo vamos a lanzar

    steps:   #pasos
          #este paso copia lo que hay en la rama main en la maquina virtual de ubuntu (lo de arriba)
      - name: Checkout   #nombre del action
        uses: actions/checkout@v4  #en el apartado de la derecha buscar el nombre del anterior aprametro y ponerle el uso (copiar y pegar)
      
      - name: Configurar credenciales aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"  # Cambia a la región de AWS que estás usando
          
          #este paso es para instalar terraform en la maquina virtual
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        id: init
        #run: terraform -chdir="Archivos tf" init -backend-config="bucket=$BUCKET_TF_STATE"
        run: terraform -chdir="Archivos tf" init  # Inicializa Terraform sin backend con el tfstate que esta en el repositorio
       
      - name: Plan Terraform
        id: plan
        run: terraform -chdir="Archivos tf" plan -var "public_key"=${{ secrets.PUBLIC_KEY }}"
        #continue-on-error: true

      - name: Terraform Apply
        env:
         #definido previamente otro secreto con la clave publica deployer-key.pub
         TF_VAR_deployer_public_key: ${{ secrets.DEPLOYER_PUBLIC_KEY }}
        run: terraform -chdir="Archivos tf" apply -auto-approve -var "public_key"=${{ secrets.PUBLIC_KEY }}"

      #- name: Subir tfstate como artefacto
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: tfstate
      #    path: "Archivos tf/terraform.tfstate" # Asegúrate de que la ruta sea correcta
